Deleted and replaced GVR.
Doesn't compile due to:
Assets/Scripts/GameManager.cs(156,44): error CS1061: Type
`GvrReticlePointer' does not contain a definition for
`reticlePointerImpl' and no extension method `reticlePointerImpl' of
type `GvrReticlePointer' could be found. Are you missing an assembly
reference?
`